# -*- coding: utf-8 -*-

import doctor_attentions_pediatrics
import doctor_patient_pediatrics_inherit
import doctor_appointment_pediatrics_inherit
import doctor_review_systems_inherit
import doctor_attentions_exam_inherit
import doctor_therapeutical_procedures_inherit
import doctor_attentions_past_inherit
import doctor_attentions_diseases_inherit